#!/usr/bin/env bash
# iso/payload/synca-install.sh
# Installs the static SyncA UTM application payload and firstboot service.

set -euo pipefail

INSTALLER_DIR="${INSTALLER_DIR:-/opt/synca-installer}"
APP_ARCHIVE="${INSTALLER_DIR}/server-gui.tar.gz"
WHEELHOUSE="${INSTALLER_DIR}/wheelhouse"
WGUI_BINARY="${INSTALLER_DIR}/wireguard-ui"
RPM_DIR="${INSTALLER_DIR}/rpms"

require_root() {
    # The installer writes /opt, /etc, and systemd units.
    if [[ "$(id -u)" -ne 0 ]]; then
        echo "synca-install must run as root" >&2
        exit 1
    fi
}

install_server_gui() {
    # The Python application is shipped as a tarball generated by the ISO build
    # script. Runtime configuration is created later by synca-firstboot.
    install -d -m 0755 /opt
    rm -rf /opt/server-gui
    install -d -m 0755 /opt/server-gui
    tar -xzf "$APP_ARCHIVE" -C /opt/server-gui
    chown -R root:root /opt/server-gui
    chmod 0755 /opt/server-gui

    python3 -m venv /opt/server-gui/venv
    if [[ -d "$WHEELHOUSE" ]] && compgen -G "$WHEELHOUSE/*.whl" >/dev/null; then
        /opt/server-gui/venv/bin/pip install --no-index --find-links "$WHEELHOUSE" \
            -r /opt/server-gui/requirements.txt
    else
        echo "Python wheelhouse is missing. Rebuild ISO with SYNC_BUILD_WHEELHOUSE=1." >&2
        exit 1
    fi
    find /opt/server-gui/bin -maxdepth 1 -type f -exec sed -i 's/\r$//' {} +
    find /opt/server-gui/bin -maxdepth 1 -type f -exec chmod +x {} +
}

install_extra_rpms() {
    # Optional local RPM closure for packages not present on the AlmaLinux DVD,
    # for example nginx-mod-modsecurity from EPEL. The build process must place
    # all dependency RPMs in this directory for fully offline installation.
    local rpm_glob=()
    if [[ -d "$RPM_DIR" ]] && compgen -G "$RPM_DIR/*.rpm" >/dev/null; then
        rpm_glob+=("$RPM_DIR"/*.rpm)
    fi
    if [[ -d "$RPM_DIR/Packages" ]] && compgen -G "$RPM_DIR/Packages/*.rpm" >/dev/null; then
        rpm_glob+=("$RPM_DIR"/Packages/*.rpm)
    fi
    if [[ "${#rpm_glob[@]}" -gt 0 ]]; then
        dnf install -y "${rpm_glob[@]}" || {
            echo "warning: optional SyncA RPM installation failed; continuing because Kickstart already installs required packages" >&2
        }
    fi
}

install_wireguard_ui() {
    # wireguard-ui is optional at ISO build time. The service is installed only
    # when the binary is present, avoiding a broken unit on minimal builds.
    install -d -m 0755 /opt/wireguard/db
    if [[ -f "$WGUI_BINARY" ]]; then
        install -m 0755 "$WGUI_BINARY" /opt/wireguard/wireguard-ui
    fi
}

install_letsencrypt_hooks() {
    install -d -m 0755 /etc/letsencrypt/renewal-hooks/pre /etc/letsencrypt/renewal-hooks/post
    cat > /etc/letsencrypt/renewal-hooks/pre/00-syncautm.sh <<'HOOK'
#!/usr/bin/env bash
set -euo pipefail
if systemctl is-active --quiet firewalld; then
    firewall-cmd --zone=public --add-service=http || true
    firewall-cmd --zone=public --add-service=https || true
fi
systemctl stop nginx.service || true
HOOK
    cat > /etc/letsencrypt/renewal-hooks/post/00-syncautm.sh <<'HOOK'
#!/usr/bin/env bash
set -euo pipefail
systemctl start nginx.service || true
if systemctl is-active --quiet firewalld; then
    firewall-cmd --zone=public --remove-service=http || true
    firewall-cmd --zone=public --remove-service=https || true
fi
HOOK
    chmod 0755 /etc/letsencrypt/renewal-hooks/pre/00-syncautm.sh \
        /etc/letsencrypt/renewal-hooks/post/00-syncautm.sh
}

install_firewalld_profile() {
    install -d -m 0755 /opt/synca-installer/firewalld-profiles
    if [[ -f "${INSTALLER_DIR}/firewalld-profiles/synca-utm-default.json" ]]; then
        if [[ "$(readlink -f "${INSTALLER_DIR}/firewalld-profiles/synca-utm-default.json")" != "/opt/synca-installer/firewalld-profiles/synca-utm-default.json" ]]; then
            install -m 0644 "${INSTALLER_DIR}/firewalld-profiles/synca-utm-default.json" \
                /opt/synca-installer/firewalld-profiles/synca-utm-default.json
        else
            chmod 0644 /opt/synca-installer/firewalld-profiles/synca-utm-default.json
        fi
    fi
}

install_private_overrides() {
    # Internal ISO builds may ship private systemd drop-ins from the build host.
    # The public repository never stores these files.
    local smtp_dropin="${INSTALLER_DIR}/private/server-gui-ddns-smtp.conf"
    if [[ -f "$smtp_dropin" ]]; then
        install -d -m 0750 /etc/systemd/system/server-gui.service.d
        install -d -m 0750 /etc/systemd/system/server-gui-ddns.service.d
        install -m 0600 "$smtp_dropin" \
            /etc/systemd/system/server-gui.service.d/30-ddns-pin-smtp.conf
        install -m 0600 "$smtp_dropin" \
            /etc/systemd/system/server-gui-ddns.service.d/30-ddns-pin-smtp.conf
    fi
}

write_systemd_units() {
    install -d -m 0755 /etc/systemd/system.conf.d
    cat > /etc/systemd/system.conf.d/99-synca-quiet-console.conf <<'CONF'
[Manager]
ShowStatus=no
CONF

    cat > /etc/systemd/system/server-gui.service <<'UNIT'
[Unit]
Description=Server GUI - SyncA UTM management
After=network-online.target nginx.service
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/opt/server-gui
Environment=SERVER_GUI_CONFIG_DIR=/etc/server-gui
Environment=PYTHONUNBUFFERED=1
ExecStart=/opt/server-gui/venv/bin/gunicorn --bind 127.0.0.1:5010 --workers 2 --timeout 60 --access-logfile - --error-logfile - 'server_gui.app:create_app()'
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
PrivateTmp=true

[Install]
WantedBy=multi-user.target
UNIT

    cat > /etc/systemd/system/server-gui-ddns.service <<'UNIT'
[Unit]
Description=server-gui DDNS update check
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=root
ExecStart=/opt/server-gui/bin/ddns-check
StandardOutput=journal
StandardError=journal
UNIT

    cat > /etc/systemd/system/server-gui-ddns.timer <<'UNIT'
[Unit]
Description=Run server-gui DDNS update check periodically

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min
Persistent=true

[Install]
WantedBy=timers.target
UNIT

    cat > /etc/systemd/system/server-gui-geoip.service <<'UNIT'
[Unit]
Description=server-gui GeoIP ipset refresh
After=network-online.target firewalld.service
Wants=network-online.target

[Service]
Type=oneshot
User=root
ExecStart=/opt/server-gui/bin/geoip-update
StandardOutput=journal
StandardError=journal
UNIT

    cat > /etc/systemd/system/server-gui-geoip.timer <<'UNIT'
[Unit]
Description=Run server-gui GeoIP ipset refresh periodically

[Timer]
OnBootSec=3min
OnUnitActiveSec=1w
Persistent=true

[Install]
WantedBy=timers.target
UNIT

    cat > /etc/systemd/system/synca-firstboot.service <<'UNIT'
[Unit]
Description=SyncA UTM first boot console setup
After=systemd-user-sessions.service network.target
Before=getty@tty1.service server-gui.service nginx.service
Conflicts=getty@tty1.service
ConditionPathExists=!/etc/synca/firstboot.done

[Service]
Type=oneshot
EnvironmentFile=-/opt/synca-installer/private/firstboot.env
ExecStart=/opt/synca-installer/synca-firstboot.sh --interactive
StandardInput=tty-force
StandardOutput=tty
StandardError=tty
TTYPath=/dev/tty1
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=yes
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
UNIT

    if [[ -x /opt/wireguard/wireguard-ui ]]; then
        cat > /etc/systemd/system/wgui-worker.service <<'UNIT'
[Unit]
Description=wireguard web ui
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/wireguard
ExecStart=/opt/wireguard/wireguard-ui
Restart=always

[Install]
WantedBy=multi-user.target
UNIT
    fi
}

main() {
    require_root
    if [[ "$(readlink -f "${INSTALLER_DIR}/synca-firstboot.sh")" != "/opt/synca-installer/synca-firstboot.sh" ]]; then
        install -m 0755 "${INSTALLER_DIR}/synca-firstboot.sh" /opt/synca-installer/synca-firstboot.sh
    else
        chmod 0755 /opt/synca-installer/synca-firstboot.sh
    fi
    write_systemd_units
    systemctl daemon-reload
    systemctl enable synca-firstboot.service
    install_extra_rpms
    install_server_gui
    install_wireguard_ui
    install_letsencrypt_hooks
    install_firewalld_profile
    install_private_overrides
    systemctl daemon-reload
}

main "$@"
