"""payload/server-gui/server_gui/modules/dhcp.py - Manage dnsmasq DHCP settings and live leases."""
from __future__ import annotations

import json
import re
import uuid
from pathlib import Path

from flask import Blueprint, Flask, current_app, jsonify, render_template, request

from ..auth import csrf_protect, login_required
from ..config_store import ConfigStore
from ..dnsmasq_apply import MODULE_NAME, apply as apply_dnsmasq, default as default_data
from ..shell import run, sudo_run
from ..validators import ValidationError, validate_interface, validate_ipv4, validate_mac

bp = Blueprint("dhcp", __name__, url_prefix="/dhcp")

LEASE_RE = re.compile(r"^\d+[smhd]?$|^infinite$", re.IGNORECASE)
OPTION_RE = re.compile(r"^[a-zA-Z0-9_\-]{1,64}$")
LEASE_FILE_CANDIDATES = (
    Path("/var/lib/misc/dnsmasq.leases"),
    Path("/var/lib/dnsmasq/dnsmasq.leases"),
    Path("/run/dnsmasq/dnsmasq.leases"),
)
LEASE_GLOB_DIRS = (
    Path("/var/lib/misc"),
    Path("/var/lib/dnsmasq"),
    Path("/run/dnsmasq"),
)
DNSMASQ_CONF = Path("/etc/dnsmasq.conf")
DNSMASQ_D = Path("/etc/dnsmasq.d")
OUR_FILE_NAME = "server-gui.conf"  # generated by dnsmasq_apply — skip when scanning
_LEASE_RELEASE_SCRIPT = r"""
import json
import os
import shutil
import stat
import subprocess
import sys
import time


def emit(payload, code=0):
    print(json.dumps(payload, ensure_ascii=False))
    sys.exit(code)


def command(argv, timeout=30):
    return subprocess.run(argv, capture_output=True, text=True, timeout=timeout, check=False)


def rollback(backups):
    for path, backup in reversed(backups):
        try:
            shutil.copy2(backup, path)
        except OSError:
            pass


payload = json.load(sys.stdin)
paths = [p for p in payload.get("paths", []) if isinstance(p, str) and p.startswith("/")]
release_all = bool(payload.get("all"))
targets = payload.get("targets") or []
target_keys = {
    (str(t.get("source", "")), str(t.get("mac", "")).lower(), str(t.get("ip", "")), str(t.get("client_id", "")))
    for t in targets
}

active_check = command(["systemctl", "is-active", "--quiet", "dnsmasq"], timeout=10)
was_active = active_check.returncode == 0
if was_active:
    test = command(["dnsmasq", "--test"], timeout=20)
    if test.returncode != 0:
        emit({
            "ok": False,
            "error": "dnsmasq --test failed before lease release",
            "stdout": test.stdout,
            "stderr": test.stderr,
        }, 1)
    stop = command(["systemctl", "stop", "dnsmasq"], timeout=30)
    if stop.returncode != 0:
        emit({
            "ok": False,
            "error": "dnsmasq stop failed before lease release",
            "stdout": stop.stdout,
            "stderr": stop.stderr,
        }, 1)

# dnsmasq は停止時にメモリ上のリースを書き戻すため、停止後にファイルを編集する。
released = []
backups = []
backup_files = []
changed_files = []
timestamp = time.strftime("%Y%m%d%H%M%S")

try:
    for path in paths:
        try:
            st = os.stat(path)
        except FileNotFoundError:
            continue
        except OSError as exc:
            raise RuntimeError(f"{path}: {exc}") from exc

        try:
            with open(path, "r", encoding="utf-8", errors="replace") as handle:
                text = handle.read()
        except OSError as exc:
            raise RuntimeError(f"{path}: {exc}") from exc

        keep_lines = []
        removed_here = []
        for line in text.splitlines():
            parts = line.strip().split()
            if len(parts) < 5:
                keep_lines.append(line)
                continue
            row = {
                "source": path,
                "expires": parts[0],
                "mac": parts[1].lower(),
                "ip": parts[2],
                "hostname": "" if parts[3] == "*" else parts[3],
                "client_id": parts[4],
            }
            key = (row["source"], row["mac"], row["ip"], row["client_id"])
            if release_all or key in target_keys:
                removed_here.append(row)
            else:
                keep_lines.append(line)

        if not removed_here:
            continue

        backup = f"{path}.synca-release-{timestamp}.bak"
        tmp = f"{path}.synca-release-{os.getpid()}.tmp"
        shutil.copy2(path, backup)
        with open(tmp, "w", encoding="utf-8") as handle:
            if keep_lines:
                handle.write("\n".join(keep_lines) + "\n")
        os.chown(tmp, st.st_uid, st.st_gid)
        os.chmod(tmp, stat.S_IMODE(st.st_mode))
        os.replace(tmp, path)
        backups.append((path, backup))
        backup_files.append(backup)
        changed_files.append(path)
        released.extend(removed_here)

    if was_active:
        start = command(["systemctl", "start", "dnsmasq"], timeout=30)
        if start.returncode != 0:
            rollback(backups)
            retry = command(["systemctl", "start", "dnsmasq"], timeout=30)
            emit({
                "ok": False,
                "error": "dnsmasq start failed after lease release; lease files were rolled back",
                "stdout": start.stdout,
                "stderr": start.stderr,
                "rollback_start_stdout": retry.stdout,
                "rollback_start_stderr": retry.stderr,
            }, 1)
except Exception as exc:
    rollback(backups)
    if was_active:
        command(["systemctl", "start", "dnsmasq"], timeout=30)
    emit({"ok": False, "error": str(exc)}, 1)

status = command(["systemctl", "is-active", "dnsmasq"], timeout=10)
emit({
    "ok": True,
    "released_count": len(released),
    "released": released,
    "changed_files": changed_files,
    "backup_files": backup_files,
    "dnsmasq_was_active": was_active,
    "dnsmasq_active": status.stdout.strip(),
})
"""


def register(app: Flask) -> None:
    app.register_blueprint(bp)


def _store() -> ConfigStore:
    return ConfigStore(current_app.config["CONFIG_DIR"])


# ---- views -------------------------------------------------------------

@bp.route("/")
@login_required
def page():
    return render_template("dhcp.html", active_tab="dhcp")


@bp.route("/api/config", methods=["GET"])
@login_required
def list_config():
    data = _store().load(MODULE_NAME, default_data())
    return jsonify({"dhcp": data.get("dhcp", {})})


@bp.route("/api/interfaces", methods=["GET"])
@login_required
def list_dhcp_interfaces():
    """List non-WAN interfaces that can be bound to a DHCP range."""
    return jsonify({"interfaces": _dhcp_interface_candidates()})


_RANGE_LEASE_RE = re.compile(r"^\d+[smhd]?$|^infinite$", re.IGNORECASE)
_MAC_RE = re.compile(r"^([0-9a-f]{2}:){5}[0-9a-f]{2}$", re.IGNORECASE)


def _parse_dhcp_range_raw(raw: str) -> dict:
    """Parse a dhcp-range value into {interface, tag, start, end, netmask, lease}.

    Handles the common shapes:
      interface:X,start,end[,netmask],lease
      set:TAG,start,end[,netmask],lease
      interface:X,set:TAG,start,end[,netmask],lease
    """
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    out = {"interface": None, "tag": "", "start": None, "end": None, "netmask": None, "lease": "12h"}
    i = 0
    while i < len(parts):
        if parts[i].startswith("interface:"):
            out["interface"] = parts[i][len("interface:"):]
            i += 1
            continue
        if parts[i].startswith("set:"):
            out["tag"] = parts[i][len("set:"):]
            i += 1
            continue
        if parts[i].startswith("tag:"):
            # tag:<name> selects a range; it is not the option-scope tag set
            # by dnsmasq. Keep parsing the address portion but do not persist it
            # as the generated set:<tag> value.
            i += 1
            continue
        break
    # start
    if i >= len(parts):
        raise ValueError("start IP がありません")
    import ipaddress
    try:
        ipaddress.IPv4Address(parts[i]); out["start"] = parts[i]; i += 1
    except ValueError:
        raise ValueError(f"start IP が不正: {parts[i]!r}")
    # end
    if i >= len(parts):
        raise ValueError("end IP がありません")
    try:
        ipaddress.IPv4Address(parts[i]); out["end"] = parts[i]; i += 1
    except ValueError:
        # could be "static" or "ra-only" — unsupported
        raise ValueError(f"end IP が不正: {parts[i]!r}")
    # optional: netmask then lease, or just lease
    while i < len(parts):
        v = parts[i]
        if _RANGE_LEASE_RE.match(v):
            out["lease"] = v
        else:
            try:
                ipaddress.IPv4Address(v)
                out["netmask"] = v
            except ValueError:
                # ignore unknown field
                pass
        i += 1
    return out


def _parse_dhcp_host_raw(raw: str) -> dict:
    """Parse dhcp-host value into {mac, ip, hostname, lease}."""
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    out = {"mac": None, "ip": None, "hostname": "", "lease": ""}
    import ipaddress
    for p in parts:
        if p.startswith(("set:", "tag:", "id:", "client:")):
            continue
        if _MAC_RE.match(p):
            out["mac"] = p.lower()
            continue
        try:
            ipaddress.IPv4Address(p)
            out["ip"] = p
            continue
        except ValueError:
            pass
        if _RANGE_LEASE_RE.match(p):
            out["lease"] = p
            continue
        # treat as hostname
        if not out["hostname"]:
            out["hostname"] = p
    if not out["mac"] or not out["ip"]:
        raise ValueError("dhcp-host parsing requires both MAC and IP")
    return out


def _parse_dhcp_option_raw(raw: str) -> dict:
    """Parse dhcp-option value into {tag, option, value}.

    Forms:
      OPTION,VALUE
      option:NAME,VALUE
      tag:TAG,OPTION,VALUE
      tag:TAG,option:NAME,VALUE
    """
    parts = [p.strip() for p in raw.split(",")]
    out = {"tag": "", "option": None, "value": None}
    if not parts:
        raise ValueError("empty dhcp-option")
    if parts[0].startswith("tag:"):
        out["tag"] = parts[0][len("tag:"):]
        parts = parts[1:]
    if not parts:
        raise ValueError("dhcp-option needs option + value")
    if parts[0].startswith("option:"):
        out["option"] = parts[0][len("option:"):]
        parts = parts[1:]
    elif parts[0].isdigit() or re.match(r"^[a-zA-Z][a-zA-Z0-9_\-]*$", parts[0]):
        out["option"] = parts[0]
        parts = parts[1:]
    else:
        raise ValueError(f"unrecognized option: {parts[0]!r}")
    if not parts:
        raise ValueError("dhcp-option needs value")
    out["value"] = ",".join(parts)
    return out


@bp.route("/api/import", methods=["POST"])
@login_required
@csrf_protect
def import_existing():
    """Import a single existing entry into the managed store. Body:
        {kind: "range"|"host"|"option", raw: "<the value after dhcp-X=>"}
    Returns the new id on success.
    """
    payload = request.get_json(force=True, silent=True) or {}
    kind = payload.get("kind")
    raw = (payload.get("raw") or "").strip()
    if kind not in ("range", "host", "option") or not raw:
        return jsonify({"error": "kind ('range'|'host'|'option') and raw required"}), 400
    new_id = uuid.uuid4().hex
    try:
        if kind == "range":
            parsed = _parse_dhcp_range_raw(raw)
            with _store().transaction(MODULE_NAME, default_data()) as data:
                data["dhcp"]["ranges"].append({"id": new_id, **parsed})
        elif kind == "host":
            parsed = _parse_dhcp_host_raw(raw)
            with _store().transaction(MODULE_NAME, default_data()) as data:
                if any(h["mac"] == parsed["mac"] for h in data["dhcp"]["static_hosts"]):
                    return jsonify({"error": f"MAC {parsed['mac']} already managed"}), 409
                data["dhcp"]["static_hosts"].append({"id": new_id, **parsed})
        else:  # option
            parsed = _parse_dhcp_option_raw(raw)
            with _store().transaction(MODULE_NAME, default_data()) as data:
                data["dhcp"]["options"].append({"id": new_id, **parsed})
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        # Roll back the import
        with _store().transaction(MODULE_NAME, default_data()) as data:
            for k in ("ranges", "static_hosts", "options"):
                data["dhcp"][k] = [r for r in data["dhcp"][k] if r["id"] != new_id]
        return jsonify({"error": str(e)}), 500
    return jsonify({
        "ok": True, "id": new_id, "parsed": parsed,
        "note": "管理対象に取り込みました。重複を避けるため、元ファイル側のエントリは手動でコメントアウトしてください。",
    }), 201


@bp.route("/api/existing", methods=["GET"])
@login_required
def list_existing():
    """Scan /etc/dnsmasq.conf and /etc/dnsmasq.d/*.conf (excluding server-gui.conf)
    for DHCP directives so users can see what's already configured outside GUI control.
    """
    sources: list[dict] = []
    ranges: list[dict] = []
    static_hosts: list[dict] = []
    options: list[dict] = []

    for p in _dnsmasq_config_files():
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        sources.append({"path": str(p), "name": p.name})
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("dhcp-range="):
                ranges.append({"source": p.name, "raw": stripped[len("dhcp-range="):]})
            elif stripped.startswith("dhcp-host="):
                static_hosts.append({"source": p.name, "raw": stripped[len("dhcp-host="):]})
            elif stripped.startswith("dhcp-option="):
                options.append({"source": p.name, "raw": stripped[len("dhcp-option="):]})

    return jsonify({
        "sources": sources,
        "ranges": ranges,
        "static_hosts": static_hosts,
        "options": options,
    })


@bp.route("/api/leases", methods=["GET"])
@login_required
def list_leases():
    """Read dnsmasq lease files across distro-specific default locations."""
    leases: list[dict] = []
    errors: list[str] = []
    checked: list[str] = []
    seen: set[tuple[str, str, str, str]] = set()
    sources: set[str] = set()

    for lease_file in _lease_file_candidates():
        checked.append(str(lease_file))
        if not lease_file.exists():
            continue
        try:
            text = lease_file.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            errors.append(f"{lease_file}: {e}")
            continue
        for lease in _parse_lease_text(text, lease_file):
            key = (lease["expires"], lease["mac"], lease["ip"], lease["client_id"])
            if key in seen:
                continue
            seen.add(key)
            sources.add(str(lease_file))
            leases.append(lease)

    if leases:
        return jsonify({"leases": leases, "sources": sorted(sources), "checked": checked})

    response = {
        "leases": [],
        "checked": checked,
        "note": "lease file not found or empty (DHCP may be inactive)",
    }
    if errors:
        response["error"] = "; ".join(errors)
    return jsonify(response)


@bp.route("/api/leases/release", methods=["POST"])
@login_required
@csrf_protect
def release_leases():
    """Release selected or all active dnsmasq leases by editing the lease DB safely."""
    payload = request.get_json(force=True, silent=True) or {}
    release_all = payload.get("all") is True
    allowed_sources = {str(path) for path in _lease_file_candidates()}
    targets = []

    if not release_all:
        raw_targets = payload.get("leases") or []
        if not isinstance(raw_targets, list) or not raw_targets:
            return jsonify({"error": "解放対象のリースを選択してください"}), 400
        for item in raw_targets:
            if not isinstance(item, dict):
                return jsonify({"error": "リース指定が不正です"}), 400
            source = str(item.get("source", "")).strip()
            if source not in allowed_sources:
                return jsonify({"error": f"許可されていないリースファイルです: {source}"}), 400
            try:
                mac = validate_mac(str(item.get("mac", "")).strip())
                ip = validate_ipv4(str(item.get("ip", "")).strip())
            except ValidationError as e:
                return jsonify({"error": str(e)}), 400
            client_id = str(item.get("client_id", "")).strip()
            if "\n" in client_id or len(client_id) > 256:
                return jsonify({"error": "client-id が不正です"}), 400
            targets.append({"source": source, "mac": mac, "ip": ip, "client_id": client_id})

    lease_files = [str(path) for path in _lease_file_candidates() if path.exists()]
    if not lease_files:
        return jsonify({
            "ok": True,
            "released_count": 0,
            "released": [],
            "note": "リースファイルが見つかりません",
        })

    # リース削除は root 権限と dnsmasq の短時間停止が必要なため、限定した Python 処理を sudo で実行する。
    result = sudo_run(
        ["python3", "-c", _LEASE_RELEASE_SCRIPT],
        stdin=json.dumps({"paths": lease_files, "all": release_all, "targets": targets}, ensure_ascii=False),
        timeout=90,
    )
    try:
        data = json.loads(result.stdout.strip() or "{}")
    except json.JSONDecodeError:
        data = {}
    if not result.ok or not data.get("ok"):
        error = data.get("error") or result.stderr.strip() or result.stdout.strip() or "lease release failed"
        return jsonify({"error": error, "stdout": result.stdout, "stderr": result.stderr}), 500
    return jsonify(data)


def _parse_lease_text(text: str, lease_file: Path) -> list[dict]:
    """Parse dnsmasq's whitespace-separated lease format."""
    leases: list[dict] = []
    for line in text.splitlines():
        parts = line.strip().split()
        if len(parts) < 5:
            continue
        leases.append({
            "expires": parts[0],
            "mac": parts[1],
            "ip": parts[2],
            "hostname": parts[3] if parts[3] != "*" else "",
            "client_id": parts[4],
            "source": str(lease_file),
        })
    return leases


def _lease_file_candidates() -> list[Path]:
    """Return configured and known dnsmasq lease-file paths without duplicates."""
    candidates: list[Path] = []
    seen: set[str] = set()

    def add(path: Path) -> None:
        key = str(path)
        if key not in seen:
            seen.add(key)
            candidates.append(path)

    for path in _configured_lease_files():
        add(path)
    for path in LEASE_FILE_CANDIDATES:
        add(path)
    for directory in LEASE_GLOB_DIRS:
        try:
            for path in sorted(directory.glob("*.leases")):
                add(path)
        except OSError:
            continue
    return candidates


def _configured_lease_files() -> list[Path]:
    """Find explicit dhcp-leasefile directives in the effective dnsmasq config set."""
    paths: list[Path] = []
    for config_file in _dnsmasq_config_files(include_generated=True):
        try:
            text = config_file.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for line in text.splitlines():
            stripped = line.split("#", 1)[0].strip()
            if not stripped.startswith("dhcp-leasefile="):
                continue
            value = stripped.partition("=")[2].strip().strip("\"'")
            if value:
                paths.append(Path(value))
    return paths


def _dnsmasq_config_files(include_generated: bool = False) -> list[Path]:
    """List dnsmasq config files in scan order."""
    candidates: list[Path] = []
    if DNSMASQ_CONF.exists():
        candidates.append(DNSMASQ_CONF)
    if DNSMASQ_D.exists():
        for p in sorted(DNSMASQ_D.glob("*.conf")):
            if not include_generated and p.name == OUR_FILE_NAME:
                continue
            candidates.append(p)
    return candidates


# ---- ranges ------------------------------------------------------------

@bp.route("/api/ranges", methods=["POST"])
@login_required
@csrf_protect
def add_range():
    payload = request.get_json(force=True, silent=True) or {}
    try:
        start = validate_ipv4(payload.get("start", ""))
        end = validate_ipv4(payload.get("end", ""))
    except ValidationError as e:
        return jsonify({"error": str(e)}), 400
    lease = str(payload.get("lease", "12h")).strip() or "12h"
    if not LEASE_RE.match(lease):
        return jsonify({"error": "invalid lease (e.g. 12h, 1d, 3600s, infinite)"}), 400
    interface = (payload.get("interface") or "").strip() or None
    if interface:
        try:
            interface = validate_interface(interface)
        except ValidationError as e:
            return jsonify({"error": str(e)}), 400
        candidates = _dhcp_interface_candidates()
        candidate_names = {item["name"] for item in candidates}
        if candidate_names and interface not in candidate_names:
            return jsonify({"error": f"interface is not eligible for DHCP range: {interface}"}), 400
    netmask = (payload.get("netmask") or "").strip() or None
    if netmask:
        try:
            validate_ipv4(netmask)
        except ValidationError as e:
            return jsonify({"error": str(e)}), 400

    new_id = uuid.uuid4().hex
    with _store().transaction(MODULE_NAME, default_data()) as data:
        data["dhcp"]["ranges"].append({
            "id": new_id, "interface": interface,
            "start": start, "end": end, "netmask": netmask, "lease": lease,
        })
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True, "id": new_id}), 201


@bp.route("/api/ranges/<rid>", methods=["DELETE"])
@login_required
@csrf_protect
def delete_range(rid: str):
    with _store().transaction(MODULE_NAME, default_data()) as data:
        before = len(data["dhcp"]["ranges"])
        data["dhcp"]["ranges"] = [h for h in data["dhcp"]["ranges"] if h["id"] != rid]
        if len(data["dhcp"]["ranges"]) == before:
            return jsonify({"error": "not found"}), 404
        data["dhcp"]["options"] = [
            item for item in data["dhcp"].get("options", [])
            if str(item.get("range_id", "")) != rid
        ]
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True})


def _dhcp_interface_candidates() -> list[dict]:
    """Return DHCP-bindable device names, excluding WAN and PPPoE parent NICs."""
    allowed_types = {"ethernet", "bridge", "vlan", "bond", "team"}
    blocked = _wan_like_interfaces()
    rows = _nmcli_terse(["-f", "DEVICE,TYPE,STATE,CONNECTION", "device"])
    ip_map = _device_ip_map()
    candidates: list[dict] = []
    for row in rows:
        if len(row) < 4:
            continue
        name, dev_type, state, connection = row[:4]
        if not name or name == "lo" or name in blocked or dev_type not in allowed_types:
            continue
        candidates.append({
            "name": name,
            "type": dev_type,
            "state": state,
            "connection": connection or "",
            "ipv4": ip_map.get(name, []),
        })
    return candidates


def _wan_like_interfaces() -> set[str]:
    """Identify default-route devices and PPPoE parent NICs that DHCP must not bind."""
    blocked: set[str] = set()
    routes = run(["ip", "-j", "route", "show", "default"])
    if routes.ok:
        try:
            for route in json.loads(routes.stdout):
                dev = route.get("dev")
                if dev:
                    blocked.add(dev)
        except json.JSONDecodeError:
            pass

    for row in _nmcli_terse(["-f", "NAME,TYPE,DEVICE", "connection", "show", "--active"]):
        if len(row) < 3 or row[1] != "pppoe":
            continue
        name = row[0]
        detail = run(["nmcli", "-t", "-e", "no", "-f", "connection.interface-name", "connection", "show", name])
        if detail.ok:
            _, _, parent = detail.stdout.strip().partition(":")
            if parent:
                blocked.add(parent)
    return blocked


def _device_ip_map() -> dict[str, list[str]]:
    """Return current IPv4 CIDR addresses by interface name."""
    res = run(["ip", "-j", "addr", "show"])
    if not res.ok:
        return {}
    try:
        data = json.loads(res.stdout)
    except json.JSONDecodeError:
        return {}
    out: dict[str, list[str]] = {}
    for entry in data:
        name = entry.get("ifname")
        if not name:
            continue
        addresses: list[str] = []
        for item in entry.get("addr_info", []):
            if item.get("family") == "inet" and item.get("local") and item.get("prefixlen") is not None:
                addresses.append(f"{item['local']}/{item['prefixlen']}")
        out[name] = addresses
    return out


def _nmcli_terse(args: list[str]) -> list[list[str]]:
    """Run nmcli terse output and split each non-empty row by colon."""
    res = run(["nmcli", "-t", "-e", "no", *args])
    if not res.ok:
        return []
    return [line.split(":") for line in res.stdout.splitlines() if line]


# ---- static hosts ------------------------------------------------------

@bp.route("/api/static-hosts", methods=["POST"])
@login_required
@csrf_protect
def add_static_host():
    payload = request.get_json(force=True, silent=True) or {}
    try:
        mac = validate_mac(payload.get("mac", ""))
        ip = validate_ipv4(payload.get("ip", ""))
    except ValidationError as e:
        return jsonify({"error": str(e)}), 400
    hostname = (payload.get("hostname") or "").strip() or ""
    lease = (payload.get("lease") or "").strip() or ""
    if lease and not LEASE_RE.match(lease):
        return jsonify({"error": "invalid lease"}), 400
    new_id = uuid.uuid4().hex
    with _store().transaction(MODULE_NAME, default_data()) as data:
        if any(h["mac"] == mac for h in data["dhcp"]["static_hosts"]):
            return jsonify({"error": f"MAC {mac} already reserved"}), 409
        data["dhcp"]["static_hosts"].append({
            "id": new_id, "mac": mac, "ip": ip, "hostname": hostname, "lease": lease,
        })
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True, "id": new_id}), 201


@bp.route("/api/static-hosts/<rid>", methods=["DELETE"])
@login_required
@csrf_protect
def delete_static_host(rid: str):
    with _store().transaction(MODULE_NAME, default_data()) as data:
        before = len(data["dhcp"]["static_hosts"])
        data["dhcp"]["static_hosts"] = [h for h in data["dhcp"]["static_hosts"] if h["id"] != rid]
        if len(data["dhcp"]["static_hosts"]) == before:
            return jsonify({"error": "not found"}), 404
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True})


# ---- DHCP options ------------------------------------------------------

@bp.route("/api/options", methods=["POST"])
@login_required
@csrf_protect
def add_option():
    payload = request.get_json(force=True, silent=True) or {}
    option = str(payload.get("option", "")).strip()
    value = str(payload.get("value", "")).strip()
    tag = str(payload.get("tag", "")).strip() or ""
    range_id = str(payload.get("range_id", "")).strip() or ""
    if not OPTION_RE.match(option):
        return jsonify({"error": "invalid option name/number"}), 400
    if not value or "\n" in value:
        return jsonify({"error": "invalid value"}), 400
    if tag and not OPTION_RE.match(tag):
        return jsonify({"error": "invalid tag"}), 400
    if range_id:
        current = _store().load(MODULE_NAME, default_data())
        range_ids = {str(item.get("id", "")) for item in current.get("dhcp", {}).get("ranges", [])}
        if range_id not in range_ids:
            return jsonify({"error": "selected DHCP range was not found"}), 400
    new_id = uuid.uuid4().hex
    with _store().transaction(MODULE_NAME, default_data()) as data:
        data["dhcp"]["options"].append({
            "id": new_id, "option": option, "value": value, "tag": tag, "range_id": range_id,
        })
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True, "id": new_id}), 201


@bp.route("/api/options/<rid>", methods=["DELETE"])
@login_required
@csrf_protect
def delete_option(rid: str):
    with _store().transaction(MODULE_NAME, default_data()) as data:
        before = len(data["dhcp"]["options"])
        data["dhcp"]["options"] = [h for h in data["dhcp"]["options"] if h["id"] != rid]
        if len(data["dhcp"]["options"]) == before:
            return jsonify({"error": "not found"}), 404
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True})
