"""DHCP section of dnsmasq (ranges, static reservations, options) + live leases."""
from __future__ import annotations

import re
import uuid
from pathlib import Path

from flask import Blueprint, Flask, current_app, jsonify, render_template, request

from ..auth import csrf_protect, login_required
from ..config_store import ConfigStore
from ..dnsmasq_apply import MODULE_NAME, apply as apply_dnsmasq, default as default_data
from ..validators import ValidationError, validate_interface, validate_ipv4, validate_mac

bp = Blueprint("dhcp", __name__, url_prefix="/dhcp")

LEASE_RE = re.compile(r"^\d+[smhd]?$|^infinite$", re.IGNORECASE)
OPTION_RE = re.compile(r"^[a-zA-Z0-9_\-]{1,64}$")
LEASES_FILE = Path("/var/lib/misc/dnsmasq.leases")
DNSMASQ_CONF = Path("/etc/dnsmasq.conf")
DNSMASQ_D = Path("/etc/dnsmasq.d")
OUR_FILE_NAME = "server-gui.conf"  # generated by dnsmasq_apply — skip when scanning


def register(app: Flask) -> None:
    app.register_blueprint(bp)


def _store() -> ConfigStore:
    return ConfigStore(current_app.config["CONFIG_DIR"])


# ---- views -------------------------------------------------------------

@bp.route("/")
@login_required
def page():
    return render_template("dhcp.html", active_tab="dhcp")


@bp.route("/api/config", methods=["GET"])
@login_required
def list_config():
    data = _store().load(MODULE_NAME, default_data())
    return jsonify({"dhcp": data.get("dhcp", {})})


_RANGE_LEASE_RE = re.compile(r"^\d+[smhd]?$|^infinite$", re.IGNORECASE)
_MAC_RE = re.compile(r"^([0-9a-f]{2}:){5}[0-9a-f]{2}$", re.IGNORECASE)


def _parse_dhcp_range_raw(raw: str) -> dict:
    """Parse a dhcp-range value into {interface, start, end, netmask, lease}.

    Handles the common shapes: 'interface:X,start,end[,netmask],lease'.
    Raises ValueError on unsupported forms (set:/tag: prefixes, IPv6, etc.).
    """
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    out = {"interface": None, "start": None, "end": None, "netmask": None, "lease": "12h"}
    i = 0
    if parts[i].startswith("interface:"):
        out["interface"] = parts[i][len("interface:"):]
        i += 1
    if parts[i].startswith(("set:", "tag:")):
        raise ValueError(f"set:/tag: 接頭辞は未対応です ({parts[i]})")
    # start
    if i >= len(parts):
        raise ValueError("start IP がありません")
    import ipaddress
    try:
        ipaddress.IPv4Address(parts[i]); out["start"] = parts[i]; i += 1
    except ValueError:
        raise ValueError(f"start IP が不正: {parts[i]!r}")
    # end
    if i >= len(parts):
        raise ValueError("end IP がありません")
    try:
        ipaddress.IPv4Address(parts[i]); out["end"] = parts[i]; i += 1
    except ValueError:
        # could be "static" or "ra-only" — unsupported
        raise ValueError(f"end IP が不正: {parts[i]!r}")
    # optional: netmask then lease, or just lease
    while i < len(parts):
        v = parts[i]
        if _RANGE_LEASE_RE.match(v):
            out["lease"] = v
        else:
            try:
                ipaddress.IPv4Address(v)
                out["netmask"] = v
            except ValueError:
                # ignore unknown field
                pass
        i += 1
    return out


def _parse_dhcp_host_raw(raw: str) -> dict:
    """Parse dhcp-host value into {mac, ip, hostname, lease}."""
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    out = {"mac": None, "ip": None, "hostname": "", "lease": ""}
    import ipaddress
    for p in parts:
        if p.startswith(("set:", "tag:", "id:", "client:")):
            continue
        if _MAC_RE.match(p):
            out["mac"] = p.lower()
            continue
        try:
            ipaddress.IPv4Address(p)
            out["ip"] = p
            continue
        except ValueError:
            pass
        if _RANGE_LEASE_RE.match(p):
            out["lease"] = p
            continue
        # treat as hostname
        if not out["hostname"]:
            out["hostname"] = p
    if not out["mac"] or not out["ip"]:
        raise ValueError("dhcp-host parsing requires both MAC and IP")
    return out


def _parse_dhcp_option_raw(raw: str) -> dict:
    """Parse dhcp-option value into {tag, option, value}.

    Forms:
      OPTION,VALUE
      option:NAME,VALUE
      tag:TAG,OPTION,VALUE
      tag:TAG,option:NAME,VALUE
    """
    parts = [p.strip() for p in raw.split(",")]
    out = {"tag": "", "option": None, "value": None}
    if not parts:
        raise ValueError("empty dhcp-option")
    if parts[0].startswith("tag:"):
        out["tag"] = parts[0][len("tag:"):]
        parts = parts[1:]
    if not parts:
        raise ValueError("dhcp-option needs option + value")
    if parts[0].startswith("option:"):
        out["option"] = parts[0][len("option:"):]
        parts = parts[1:]
    elif parts[0].isdigit() or re.match(r"^[a-zA-Z][a-zA-Z0-9_\-]*$", parts[0]):
        out["option"] = parts[0]
        parts = parts[1:]
    else:
        raise ValueError(f"unrecognized option: {parts[0]!r}")
    if not parts:
        raise ValueError("dhcp-option needs value")
    out["value"] = ",".join(parts)
    return out


@bp.route("/api/import", methods=["POST"])
@login_required
@csrf_protect
def import_existing():
    """Import a single existing entry into the managed store. Body:
        {kind: "range"|"host"|"option", raw: "<the value after dhcp-X=>"}
    Returns the new id on success.
    """
    payload = request.get_json(force=True, silent=True) or {}
    kind = payload.get("kind")
    raw = (payload.get("raw") or "").strip()
    if kind not in ("range", "host", "option") or not raw:
        return jsonify({"error": "kind ('range'|'host'|'option') and raw required"}), 400
    new_id = uuid.uuid4().hex
    try:
        if kind == "range":
            parsed = _parse_dhcp_range_raw(raw)
            with _store().transaction(MODULE_NAME, default_data()) as data:
                data["dhcp"]["ranges"].append({"id": new_id, **parsed})
        elif kind == "host":
            parsed = _parse_dhcp_host_raw(raw)
            with _store().transaction(MODULE_NAME, default_data()) as data:
                if any(h["mac"] == parsed["mac"] for h in data["dhcp"]["static_hosts"]):
                    return jsonify({"error": f"MAC {parsed['mac']} already managed"}), 409
                data["dhcp"]["static_hosts"].append({"id": new_id, **parsed})
        else:  # option
            parsed = _parse_dhcp_option_raw(raw)
            with _store().transaction(MODULE_NAME, default_data()) as data:
                data["dhcp"]["options"].append({"id": new_id, **parsed})
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        # Roll back the import
        with _store().transaction(MODULE_NAME, default_data()) as data:
            for k in ("ranges", "static_hosts", "options"):
                data["dhcp"][k] = [r for r in data["dhcp"][k] if r["id"] != new_id]
        return jsonify({"error": str(e)}), 500
    return jsonify({
        "ok": True, "id": new_id, "parsed": parsed,
        "note": "管理対象に取り込みました。重複を避けるため、元ファイル側のエントリは手動でコメントアウトしてください。",
    }), 201


@bp.route("/api/existing", methods=["GET"])
@login_required
def list_existing():
    """Scan /etc/dnsmasq.conf and /etc/dnsmasq.d/*.conf (excluding server-gui.conf)
    for DHCP directives so users can see what's already configured outside GUI control.
    """
    sources: list[dict] = []
    ranges: list[dict] = []
    static_hosts: list[dict] = []
    options: list[dict] = []

    candidates: list[Path] = []
    if DNSMASQ_CONF.exists():
        candidates.append(DNSMASQ_CONF)
    if DNSMASQ_D.exists():
        for p in sorted(DNSMASQ_D.glob("*.conf")):
            if p.name == OUR_FILE_NAME:
                continue
            candidates.append(p)

    for p in candidates:
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        sources.append({"path": str(p), "name": p.name})
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("dhcp-range="):
                ranges.append({"source": p.name, "raw": stripped[len("dhcp-range="):]})
            elif stripped.startswith("dhcp-host="):
                static_hosts.append({"source": p.name, "raw": stripped[len("dhcp-host="):]})
            elif stripped.startswith("dhcp-option="):
                options.append({"source": p.name, "raw": stripped[len("dhcp-option="):]})

    return jsonify({
        "sources": sources,
        "ranges": ranges,
        "static_hosts": static_hosts,
        "options": options,
    })


@bp.route("/api/leases", methods=["GET"])
@login_required
def list_leases():
    """Read /var/lib/misc/dnsmasq.leases (whitespace-separated)."""
    leases: list[dict] = []
    if not LEASES_FILE.exists():
        return jsonify({"leases": [], "note": "lease file not found (DHCP not active?)"})
    try:
        text = LEASES_FILE.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return jsonify({"leases": [], "error": str(e)})
    for line in text.splitlines():
        parts = line.strip().split()
        if len(parts) < 5:
            continue
        leases.append({
            "expires": parts[0],
            "mac": parts[1],
            "ip": parts[2],
            "hostname": parts[3] if parts[3] != "*" else "",
            "client_id": parts[4],
        })
    return jsonify({"leases": leases})


# ---- ranges ------------------------------------------------------------

@bp.route("/api/ranges", methods=["POST"])
@login_required
@csrf_protect
def add_range():
    payload = request.get_json(force=True, silent=True) or {}
    try:
        start = validate_ipv4(payload.get("start", ""))
        end = validate_ipv4(payload.get("end", ""))
    except ValidationError as e:
        return jsonify({"error": str(e)}), 400
    lease = str(payload.get("lease", "12h")).strip() or "12h"
    if not LEASE_RE.match(lease):
        return jsonify({"error": "invalid lease (e.g. 12h, 1d, 3600s, infinite)"}), 400
    interface = (payload.get("interface") or "").strip() or None
    if interface:
        try:
            interface = validate_interface(interface)
        except ValidationError as e:
            return jsonify({"error": str(e)}), 400
    netmask = (payload.get("netmask") or "").strip() or None
    if netmask:
        try:
            validate_ipv4(netmask)
        except ValidationError as e:
            return jsonify({"error": str(e)}), 400

    new_id = uuid.uuid4().hex
    with _store().transaction(MODULE_NAME, default_data()) as data:
        data["dhcp"]["ranges"].append({
            "id": new_id, "interface": interface,
            "start": start, "end": end, "netmask": netmask, "lease": lease,
        })
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True, "id": new_id}), 201


@bp.route("/api/ranges/<rid>", methods=["DELETE"])
@login_required
@csrf_protect
def delete_range(rid: str):
    with _store().transaction(MODULE_NAME, default_data()) as data:
        before = len(data["dhcp"]["ranges"])
        data["dhcp"]["ranges"] = [h for h in data["dhcp"]["ranges"] if h["id"] != rid]
        if len(data["dhcp"]["ranges"]) == before:
            return jsonify({"error": "not found"}), 404
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True})


# ---- static hosts ------------------------------------------------------

@bp.route("/api/static-hosts", methods=["POST"])
@login_required
@csrf_protect
def add_static_host():
    payload = request.get_json(force=True, silent=True) or {}
    try:
        mac = validate_mac(payload.get("mac", ""))
        ip = validate_ipv4(payload.get("ip", ""))
    except ValidationError as e:
        return jsonify({"error": str(e)}), 400
    hostname = (payload.get("hostname") or "").strip() or ""
    lease = (payload.get("lease") or "").strip() or ""
    if lease and not LEASE_RE.match(lease):
        return jsonify({"error": "invalid lease"}), 400
    new_id = uuid.uuid4().hex
    with _store().transaction(MODULE_NAME, default_data()) as data:
        if any(h["mac"] == mac for h in data["dhcp"]["static_hosts"]):
            return jsonify({"error": f"MAC {mac} already reserved"}), 409
        data["dhcp"]["static_hosts"].append({
            "id": new_id, "mac": mac, "ip": ip, "hostname": hostname, "lease": lease,
        })
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True, "id": new_id}), 201


@bp.route("/api/static-hosts/<rid>", methods=["DELETE"])
@login_required
@csrf_protect
def delete_static_host(rid: str):
    with _store().transaction(MODULE_NAME, default_data()) as data:
        before = len(data["dhcp"]["static_hosts"])
        data["dhcp"]["static_hosts"] = [h for h in data["dhcp"]["static_hosts"] if h["id"] != rid]
        if len(data["dhcp"]["static_hosts"]) == before:
            return jsonify({"error": "not found"}), 404
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True})


# ---- DHCP options ------------------------------------------------------

@bp.route("/api/options", methods=["POST"])
@login_required
@csrf_protect
def add_option():
    payload = request.get_json(force=True, silent=True) or {}
    option = str(payload.get("option", "")).strip()
    value = str(payload.get("value", "")).strip()
    tag = str(payload.get("tag", "")).strip() or ""
    if not OPTION_RE.match(option):
        return jsonify({"error": "invalid option name/number"}), 400
    if not value or "\n" in value:
        return jsonify({"error": "invalid value"}), 400
    if tag and not OPTION_RE.match(tag):
        return jsonify({"error": "invalid tag"}), 400
    new_id = uuid.uuid4().hex
    with _store().transaction(MODULE_NAME, default_data()) as data:
        data["dhcp"]["options"].append({
            "id": new_id, "option": option, "value": value, "tag": tag,
        })
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True, "id": new_id}), 201


@bp.route("/api/options/<rid>", methods=["DELETE"])
@login_required
@csrf_protect
def delete_option(rid: str):
    with _store().transaction(MODULE_NAME, default_data()) as data:
        before = len(data["dhcp"]["options"])
        data["dhcp"]["options"] = [h for h in data["dhcp"]["options"] if h["id"] != rid]
        if len(data["dhcp"]["options"]) == before:
            return jsonify({"error": "not found"}), 404
    try:
        apply_dnsmasq(current_app.config["CONFIG_DIR"])
    except RuntimeError as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True})
